// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: warehouse.proto

package warehousepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type AddInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInventoryRequest) Reset() {
	*x = AddInventoryRequest{}
	mi := &file_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInventoryRequest) ProtoMessage() {}

func (x *AddInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInventoryRequest.ProtoReflect.Descriptor instead.
func (*AddInventoryRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *AddInventoryRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AddInventoryRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *AddInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInventoryResponse) Reset() {
	*x = AddInventoryResponse{}
	mi := &file_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInventoryResponse) ProtoMessage() {}

func (x *AddInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInventoryResponse.ProtoReflect.Descriptor instead.
func (*AddInventoryResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *AddInventoryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *GetInventoryResponse) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *GetInventoryResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_warehouse_proto protoreflect.FileDescriptor

const file_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x0fwarehouse.proto\x12\twarehouse\"g\n" +
	"\x13AddInventoryRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\".\n" +
	"\x14AddInventoryResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\".\n" +
	"\x13GetInventoryRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"O\n" +
	"\x14GetInventoryResponse\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity2\xb4\x01\n" +
	"\x10WarehouseService\x12O\n" +
	"\fAddInventory\x12\x1e.warehouse.AddInventoryRequest\x1a\x1f.warehouse.AddInventoryResponse\x12O\n" +
	"\fGetInventory\x12\x1e.warehouse.GetInventoryRequest\x1a\x1f.warehouse.GetInventoryResponseB\x1fZ\x1dwarehouse-service/warehousepbb\x06proto3"

var (
	file_warehouse_proto_rawDescOnce sync.Once
	file_warehouse_proto_rawDescData []byte
)

func file_warehouse_proto_rawDescGZIP() []byte {
	file_warehouse_proto_rawDescOnce.Do(func() {
		file_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warehouse_proto_rawDesc), len(file_warehouse_proto_rawDesc)))
	})
	return file_warehouse_proto_rawDescData
}

var file_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_warehouse_proto_goTypes = []any{
	(*AddInventoryRequest)(nil),  // 0: warehouse.AddInventoryRequest
	(*AddInventoryResponse)(nil), // 1: warehouse.AddInventoryResponse
	(*GetInventoryRequest)(nil),  // 2: warehouse.GetInventoryRequest
	(*GetInventoryResponse)(nil), // 3: warehouse.GetInventoryResponse
}
var file_warehouse_proto_depIdxs = []int32{
	0, // 0: warehouse.WarehouseService.AddInventory:input_type -> warehouse.AddInventoryRequest
	2, // 1: warehouse.WarehouseService.GetInventory:input_type -> warehouse.GetInventoryRequest
	1, // 2: warehouse.WarehouseService.AddInventory:output_type -> warehouse.AddInventoryResponse
	3, // 3: warehouse.WarehouseService.GetInventory:output_type -> warehouse.GetInventoryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warehouse_proto_init() }
func file_warehouse_proto_init() {
	if File_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warehouse_proto_rawDesc), len(file_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warehouse_proto_goTypes,
		DependencyIndexes: file_warehouse_proto_depIdxs,
		MessageInfos:      file_warehouse_proto_msgTypes,
	}.Build()
	File_warehouse_proto = out.File
	file_warehouse_proto_goTypes = nil
	file_warehouse_proto_depIdxs = nil
}
